#!/usr/bin/env bash

# Default values
API_URL="https://data.bioontology.org"
STARTER_ONTOLOGY="STY"
IMAGE_REPOSITORY="agroportal"
IMAGE_TAG="development"
PROVISION=true # Set the default value to true

# Function to display help message
display_help() {
    echo "Start an empty Ontoportal API with only admin user and the STY ontology. Mostly used for the UI tests."
    echo "This script is deprecated and will be removed. Use instead ./ontoportal --help"
    echo "Usage: $0 [-k API_KEY] [-u API_URL] [-r IMAGE_REPOSITORY] [-t IMAGE_TAG] [-s STARTER_ONTOLOGY] [--no-provision]"
    exit 0
}

# Parse command line options
while getopts ":k:u:r:t:s:-:h" opt; do
    case $opt in
    k) API_KEY="$OPTARG" ;;
    u) API_URL="$OPTARG" ;;
    r) IMAGE_REPOSITORY="$OPTARG" ;;
    t) IMAGE_TAG="$OPTARG" ;;
    s) STARTER_ONTOLOGY="$OPTARG" ;;
    h) display_help ;;
    -) case "${OPTARG}" in
        no-provision) PROVISION=false ;;
        help) display_help ;;
        esac ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
done

# Check if required arguments are provided
if [ -z "$API_KEY" ]; then
    echo "Error: Missing required argument. Please provide API_KEY."
    echo "See help using -h, --help"
    exit 1
fi

echo "Running the Ontoportal API and CRON Setup..."

# Copy .env.sample to .env
if ! cp .env.sample .env; then
    echo "Error: Failed to copy .env.sample to .env."
    exit 1
fi

# Update a KEY=VALUE line in the .env file
set_env_var() {
    echo "Updating $1 in .env file..."
    awk -v key="$1" -v value="$2" 'index($0, key "=") == 1 {$0 = key "=" value} 1' .env >temp && mv temp .env
}

set_env_var "OP_APIKEY" "$API_KEY"
set_env_var "OP_API_URL" "$API_URL"
set_env_var "STARTER_ONTOLOGY" "$STARTER_ONTOLOGY"
set_env_var "IMAGE_REPOSITORY" "$IMAGE_REPOSITORY"
set_env_var "IMAGE_TAG" "$IMAGE_TAG"


if [ "$PROVISION" = false ]; then
    bin/run_api.sh start --no-provision
else
    bin/run_api.sh start
fi

